# Generated by Django 5.1.2 on 2024-11-03 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Model id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('name_ru', models.CharField(max_length=128, null=True)),
                ('name_uz', models.CharField(max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Model id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('question', models.TextField(verbose_name='Question')),
                ('question_en', models.TextField(null=True, verbose_name='Question')),
                ('question_ru', models.TextField(null=True, verbose_name='Question')),
                ('question_uz', models.TextField(null=True, verbose_name='Question')),
                ('answers', models.JSONField(default=[], verbose_name='Answers')),
                ('answers_en', models.JSONField(default=[], null=True, verbose_name='Answers')),
                ('answers_ru', models.JSONField(default=[], null=True, verbose_name='Answers')),
                ('answers_uz', models.JSONField(default=[], null=True, verbose_name='Answers')),
                ('correct_answer', models.CharField(max_length=1, verbose_name='Correct answer')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Model id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=128, verbose_name='Titile')),
                ('title_en', models.CharField(max_length=128, null=True, verbose_name='Titile')),
                ('title_ru', models.CharField(max_length=128, null=True, verbose_name='Titile')),
                ('title_uz', models.CharField(max_length=128, null=True, verbose_name='Titile')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_uz', models.TextField(null=True, verbose_name='Description')),
                ('quetsion_counts', models.PositiveIntegerField(default=5, verbose_name='Question counts')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('students', models.ManyToManyField(related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='Students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Model id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('correct_answers_count', models.PositiveIntegerField(default=0, verbose_name='Correct answers count')),
                ('wrong_answers_count', models.PositiveIntegerField(default=0, verbose_name='Wrong answers count')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Percentage')),
                ('is_pass', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='exam.exam', verbose_name='Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Model id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user_answer', models.CharField(max_length=1, verbose_name='User answer')),
                ('is_ture', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_items', to='exam.question', verbose_name='Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exam.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test item',
                'verbose_name_plural': 'Test items',
            },
        ),
    ]
