# Generated by Django 5.1.2 on 2024-11-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.JSONField(default=list, verbose_name='Answers'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers_en',
            field=models.JSONField(default=list, null=True, verbose_name='Answers'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers_ru',
            field=models.JSONField(default=list, null=True, verbose_name='Answers'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers_uz',
            field=models.JSONField(default=list, null=True, verbose_name='Answers'),
        ),
    ]
