# Generated by Django 5.1.2 on 2024-11-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_question_answers_alter_question_answers_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='pass_percentage',
            field=models.FloatField(default=0.0, verbose_name='Pass percentage'),
        ),
    ]
