# Generated by Django 5.1.2 on 2024-11-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_pass_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='quetsion_counts',
            new_name='question_counts',
        ),
    ]
