# Generated by Django 5.1.2 on 2024-11-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_testitem_user_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testitem',
            old_name='is_ture',
            new_name='is_true',
        ),
    ]
